# Generated by Django 5.2.8 on 2026-01-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_employee_email_employee_phone_guest_decument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
    ]
