# Generated by Django 5.2.8 on 2026-01-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_employee_email_alter_employee_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True, null=True, verbose_name='إتاحة الغرفة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='رقم الغرفة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='سعر الغرفة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('duble', 'Duble'), ('suite', 'Suite')], max_length=8, null=True, verbose_name='نوع الغرفة'),
        ),
    ]
