# Generated by Django 5.2.8 on 2026-01-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_room_is_available_alter_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الصورة'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان الصورة'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الفيديو'),
        ),
    ]
