# Generated by Django 5.2.8 on 2026-01-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
