# Generated by Django 5.2.8 on 2026-01-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_booking_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
